# Generated by Django 3.2.13 on 2022-04-29 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usersapp', '0002_auto_20220424_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=64)),
                ('repo_link', models.URLField()),
                ('users_of_project', models.ManyToManyField(to='usersapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField(max_length=1000)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField()),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='todoapp.project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usersapp.user')),
            ],
        ),
    ]
