# Generated by Django 3.2.13 on 2022-06-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0003_auto_20220602_1947'),
        ('todoapp', '0002_alter_project_repo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='users_of_project',
            field=models.ManyToManyField(blank=True, null=True, to='usersapp.User'),
        ),
    ]
